apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: python-app
spec:
  project: default

  source:
    repoURL: https://github.com/hossam1975/app-payhon.git
    targetRevision: main
    path: k8s-manifests   # مهم: خلي path يحدد المجلد اللي فيه الـ manifests

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
